version: '3'

services:
  phoneplan.api:
    image: phoneplan.api:latest
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - phoneplan.api-network      

networks: 
    phoneplan.api-network:
        driver: bridge